name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -- BƯỚC MỚI THÊM VÀO ĐÂY --
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Sửa lại số 21 nếu dự án của bạn dùng Java 17 hoặc bản khác
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn clean package -DskipTests
      # ----------------------------

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/demo-cicd:latest
